general.import = ["~/.cache/wal/colors-alacritty.toml"]

[env]
TERM = "alacritty"
LANG = "en_GB.UTF-8"
LC_CTYPE = "en_GB.UTF-8"

[font]
size = 15.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 15000

[window]
opacity = 0.8
decorations = "full"

